name: Build
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn install

      - name: Run swagger-ui generate ğŸ³
        run: yarn swagger:build
      

      - name: echo "$GITHUB_REF"
        run: echo "$GITHUB_REF"

      - name: echo "$GITHUB_TOKEN"
        run: echo "$GITHUB_TOKEN"

      - name: echo "$GITHUB_REPOSITORY"
        run: echo "$GITHUB_REPOSITORY"
        
      - name: echo "$GITHUB_ACTOR"
        run: echo "$GITHUB_ACTOR"

      # å‚è€ƒï¼šhttps://zenn.dev/lollipop_onl/articles/eoz-gha-push-diffs
      - name: Push diff
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git remote -v; \
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@arsaga.jp"
          git add .; \
          git commit -m "ãƒ†ã‚¹ãƒˆ from github actions"; \
          git push origin HEAD:${{ github.head_ref }}; \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}